version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: price-db
    restart: always
    environment:
      POSTGRES_DB: price_processor
      POSTGRES_USER: price_user
      POSTGRES_PASSWORD: price_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: